services:
  # Database Postgres per Kong
  postgres:
    image: postgres:13
    container_name: kong-postgres
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    ports:
      - "5432:5432"

  # Kong Gateway
  kong:
    image: kong:3.9.0
    container_name: kong
    user: "root"
    depends_on:
      - postgres
    ports:
      - "8000:8000"   # Proxy
      - "8443:8443"   # Proxy SSL
      - "8001:8001"   # Admin API
      - "8002:8002"   # Kong Manager
      - "8444:8444"   # Admin API SSL
    environment:
      # Configurazione DB
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong

      # Log
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr

      # log level
      KONG_LOG_LEVEL: debug

      # Admin API
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl

      KONG_PLUGINS: bundled,kong-ai-spam-filter

    volumes:
      - ../:/usr/local/kong/custom-plugins

    command: >
      sh -c "
      sleep 5 &&
      cd /usr/local/kong/custom-plugins/plugin/ &&
      luarocks make &&
      cd &&
      kong migrations bootstrap && 
      kong migrations up &&
      kong migrations finish &&
      export KONG_LOG_LEVEL=debug &&
      kong start
      "

