name: CI

on: workflow_dispatch

jobs:
  lint:
    name: Lint Lua files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1
        with:
          args: plugin/ --globals kong --globals ngx -u --no-max-code-line-length

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Hurl
        run: |
          curl -LO https://github.com/Orange-OpenSource/hurl/releases/download/2.0.1/hurl_2.0.1_amd64.deb
          sudo dpkg -i hurl_2.0.1_amd64.deb
          
      - name: Setup Docker Compose
        run: |
          docker --version
      
      - name: Start Docker Compose
        run: |
          cd docker/
          docker compose up -d
          # Wait for Kong to be ready
          echo "Waiting for Kong to be ready..."
          timeout 60 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8001)" != "200" ]]; do sleep 2; done' || exit 1
          echo "Kong is ready!"
      
      - name: Run setup script
        run: |
          hurl --variable GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
               --variable OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
               --variable ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }} \
               tests/000_setup.hurl
          env
          sleep 10

      - name: Run spam tests
        run: |
          hurl tests/003_spam_simple.hurl
          
      - name: Stop Docker Compose
        run: |
          cd docker/
          docker compose down
        if: always()
